<?php
/**
 * ChainStatus
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  IdeaEngine\TezosSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 11.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IdeaEngine\TezosSDK\Model;
use \IdeaEngine\TezosSDK\ObjectSerializer;

/**
 * ChainStatus Class Doc Comment
 *
 * @category Class
 * @description If &#39;unsynced&#39;, the node is not currently synchronized with of its peers (it is probably still bootstrapping and its head is lagging behind the chain&#39;s). If &#39;synced&#39;, the node considers itself synchronized with its peers and the current head timestamp is recent. If &#39;stuck&#39;, the node considers itself synchronized with its peers but the chain seems to be halted from its viewpoint.
 * @package  IdeaEngine\TezosSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ChainStatus
{
    /**
     * Possible values of this enum
     */
    const STUCK = 'stuck';

    const SYNCED = 'synced';

    const UNSYNCED = 'unsynced';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::STUCK,
            self::SYNCED,
            self::UNSYNCED
        ];
    }
}


