<?php
/**
 * ChainUpdate
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  IdeaEngine\TezosSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 11.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IdeaEngine\TezosSDK\Model;
use \IdeaEngine\TezosSDK\ObjectSerializer;

/**
 * ChainUpdate Class Doc Comment
 *
 * @category Class
 * @description If &#39;ignored&#39;, the new validated block is ignored since the current head fitness is better. If &#39;branch&#39;, we have set our head to a new validated block which is not the direct successor of the previous head. If &#39;increment&#39;, the new validated head is the direct successor of the previous head.
 * @package  IdeaEngine\TezosSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ChainUpdate
{
    /**
     * Possible values of this enum
     */
    const BRANCH = 'branch';

    const IGNORED = 'ignored';

    const INCREMENT = 'increment';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BRANCH,
            self::IGNORED,
            self::INCREMENT
        ];
    }
}


