<?php
/**
 * InlineResponse2004P2pGreylistingConfig
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  IdeaEngine\TezosSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 11.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IdeaEngine\TezosSDK\Model;

use \ArrayAccess;
use \IdeaEngine\TezosSDK\ObjectSerializer;

/**
 * InlineResponse2004P2pGreylistingConfig Class Doc Comment
 *
 * @category Class
 * @description The reconnection policy regulates the frequency with which the node tries to reconnect to an old known peer.
 * @package  IdeaEngine\TezosSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class InlineResponse2004P2pGreylistingConfig implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'inline_response_200_4_p2p_greylisting_config';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'factor' => 'int',
        'initial_delay' => 'OneOfInteger',
        'disconnection_delay' => 'OneOfInteger',
        'increase_cap' => 'OneOfInteger'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'factor' => null,
        'initial_delay' => null,
        'disconnection_delay' => null,
        'increase_cap' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'factor' => 'factor',
        'initial_delay' => 'initial-delay',
        'disconnection_delay' => 'disconnection-delay',
        'increase_cap' => 'increase-cap'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'factor' => 'setFactor',
        'initial_delay' => 'setInitialDelay',
        'disconnection_delay' => 'setDisconnectionDelay',
        'increase_cap' => 'setIncreaseCap'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'factor' => 'getFactor',
        'initial_delay' => 'getInitialDelay',
        'disconnection_delay' => 'getDisconnectionDelay',
        'increase_cap' => 'getIncreaseCap'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['factor'] = $data['factor'] ?? null;
        $this->container['initial_delay'] = $data['initial_delay'] ?? null;
        $this->container['disconnection_delay'] = $data['disconnection_delay'] ?? null;
        $this->container['increase_cap'] = $data['increase_cap'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets factor
     *
     * @return int|null
     */
    public function getFactor()
    {
        return $this->container['factor'];
    }

    /**
     * Sets factor
     *
     * @param int|null $factor The factor by which the reconnection delay is increased when a peer that was previously disconnected is disconnected again. This value should be set to 1 for a linear back-off and to >1 for an exponential back-off.
     *
     * @return self
     */
    public function setFactor($factor)
    {
        $this->container['factor'] = $factor;

        return $this;
    }

    /**
     * Gets initial_delay
     *
     * @return OneOfInteger|null
     */
    public function getInitialDelay()
    {
        return $this->container['initial_delay'];
    }

    /**
     * Sets initial_delay
     *
     * @param OneOfInteger|null $initial_delay The span of time a peer is disconnected for when it is first disconnected.
     *
     * @return self
     */
    public function setInitialDelay($initial_delay)
    {
        $this->container['initial_delay'] = $initial_delay;

        return $this;
    }

    /**
     * Gets disconnection_delay
     *
     * @return OneOfInteger|null
     */
    public function getDisconnectionDelay()
    {
        return $this->container['disconnection_delay'];
    }

    /**
     * Sets disconnection_delay
     *
     * @param OneOfInteger|null $disconnection_delay The span of time a peer is disconnected for when it is disconnected as the result of an error.
     *
     * @return self
     */
    public function setDisconnectionDelay($disconnection_delay)
    {
        $this->container['disconnection_delay'] = $disconnection_delay;

        return $this;
    }

    /**
     * Gets increase_cap
     *
     * @return OneOfInteger|null
     */
    public function getIncreaseCap()
    {
        return $this->container['increase_cap'];
    }

    /**
     * Sets increase_cap
     *
     * @param OneOfInteger|null $increase_cap The maximum amount by which the reconnection is extended. This limits the rate of the exponential back-off, which eventually becomes linear when it reaches this limit. This limit is set to avoid reaching the End-of-Time when repeatedly reconnection a peer.
     *
     * @return self
     */
    public function setIncreaseCap($increase_cap)
    {
        $this->container['increase_cap'] = $increase_cap;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


