<?php
/**
 * InlineResponse2009
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  IdeaEngine\TezosSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 11.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IdeaEngine\TezosSDK\Model;

use \ArrayAccess;
use \IdeaEngine\TezosSDK\ObjectSerializer;

/**
 * InlineResponse2009 Class Doc Comment
 *
 * @category Class
 * @package  IdeaEngine\TezosSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class InlineResponse2009 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'inline_response_200_9';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'score' => 'int',
        'trusted' => 'bool',
        'conn_metadata' => '\IdeaEngine\TezosSDK\Model\NetworkConnectionsLocalMetadata',
        'peer_metadata' => '\IdeaEngine\TezosSDK\Model\InlineResponse2009PeerMetadata',
        'state' => '\IdeaEngine\TezosSDK\Model\P2pPeerState',
        'reachable_at' => '\IdeaEngine\TezosSDK\Model\P2pConnectionId',
        'stat' => '\IdeaEngine\TezosSDK\Model\P2pStat',
        'last_failed_connection' => 'OneOfP2pConnectionIdTimestampSystem[]',
        'last_rejected_connection' => 'OneOfP2pConnectionIdTimestampSystem[]',
        'last_established_connection' => 'OneOfP2pConnectionIdTimestampSystem[]',
        'last_disconnection' => 'OneOfP2pConnectionIdTimestampSystem[]',
        'last_seen' => 'OneOfP2pConnectionIdTimestampSystem[]',
        'last_miss' => 'OneOfP2pConnectionIdTimestampSystem[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'score' => null,
        'trusted' => null,
        'conn_metadata' => null,
        'peer_metadata' => null,
        'state' => null,
        'reachable_at' => null,
        'stat' => null,
        'last_failed_connection' => null,
        'last_rejected_connection' => null,
        'last_established_connection' => null,
        'last_disconnection' => null,
        'last_seen' => null,
        'last_miss' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'score' => 'score',
        'trusted' => 'trusted',
        'conn_metadata' => 'conn_metadata',
        'peer_metadata' => 'peer_metadata',
        'state' => 'state',
        'reachable_at' => 'reachable_at',
        'stat' => 'stat',
        'last_failed_connection' => 'last_failed_connection',
        'last_rejected_connection' => 'last_rejected_connection',
        'last_established_connection' => 'last_established_connection',
        'last_disconnection' => 'last_disconnection',
        'last_seen' => 'last_seen',
        'last_miss' => 'last_miss'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'score' => 'setScore',
        'trusted' => 'setTrusted',
        'conn_metadata' => 'setConnMetadata',
        'peer_metadata' => 'setPeerMetadata',
        'state' => 'setState',
        'reachable_at' => 'setReachableAt',
        'stat' => 'setStat',
        'last_failed_connection' => 'setLastFailedConnection',
        'last_rejected_connection' => 'setLastRejectedConnection',
        'last_established_connection' => 'setLastEstablishedConnection',
        'last_disconnection' => 'setLastDisconnection',
        'last_seen' => 'setLastSeen',
        'last_miss' => 'setLastMiss'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'score' => 'getScore',
        'trusted' => 'getTrusted',
        'conn_metadata' => 'getConnMetadata',
        'peer_metadata' => 'getPeerMetadata',
        'state' => 'getState',
        'reachable_at' => 'getReachableAt',
        'stat' => 'getStat',
        'last_failed_connection' => 'getLastFailedConnection',
        'last_rejected_connection' => 'getLastRejectedConnection',
        'last_established_connection' => 'getLastEstablishedConnection',
        'last_disconnection' => 'getLastDisconnection',
        'last_seen' => 'getLastSeen',
        'last_miss' => 'getLastMiss'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['score'] = $data['score'] ?? null;
        $this->container['trusted'] = $data['trusted'] ?? null;
        $this->container['conn_metadata'] = $data['conn_metadata'] ?? null;
        $this->container['peer_metadata'] = $data['peer_metadata'] ?? null;
        $this->container['state'] = $data['state'] ?? null;
        $this->container['reachable_at'] = $data['reachable_at'] ?? null;
        $this->container['stat'] = $data['stat'] ?? null;
        $this->container['last_failed_connection'] = $data['last_failed_connection'] ?? null;
        $this->container['last_rejected_connection'] = $data['last_rejected_connection'] ?? null;
        $this->container['last_established_connection'] = $data['last_established_connection'] ?? null;
        $this->container['last_disconnection'] = $data['last_disconnection'] ?? null;
        $this->container['last_seen'] = $data['last_seen'] ?? null;
        $this->container['last_miss'] = $data['last_miss'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['score'] === null) {
            $invalidProperties[] = "'score' can't be null";
        }
        if ($this->container['trusted'] === null) {
            $invalidProperties[] = "'trusted' can't be null";
        }
        if ($this->container['peer_metadata'] === null) {
            $invalidProperties[] = "'peer_metadata' can't be null";
        }
        if ($this->container['state'] === null) {
            $invalidProperties[] = "'state' can't be null";
        }
        if ($this->container['stat'] === null) {
            $invalidProperties[] = "'stat' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets score
     *
     * @return int
     */
    public function getScore()
    {
        return $this->container['score'];
    }

    /**
     * Sets score
     *
     * @param int $score score
     *
     * @return self
     */
    public function setScore($score)
    {
        $this->container['score'] = $score;

        return $this;
    }

    /**
     * Gets trusted
     *
     * @return bool
     */
    public function getTrusted()
    {
        return $this->container['trusted'];
    }

    /**
     * Sets trusted
     *
     * @param bool $trusted trusted
     *
     * @return self
     */
    public function setTrusted($trusted)
    {
        $this->container['trusted'] = $trusted;

        return $this;
    }

    /**
     * Gets conn_metadata
     *
     * @return \IdeaEngine\TezosSDK\Model\NetworkConnectionsLocalMetadata|null
     */
    public function getConnMetadata()
    {
        return $this->container['conn_metadata'];
    }

    /**
     * Sets conn_metadata
     *
     * @param \IdeaEngine\TezosSDK\Model\NetworkConnectionsLocalMetadata|null $conn_metadata conn_metadata
     *
     * @return self
     */
    public function setConnMetadata($conn_metadata)
    {
        $this->container['conn_metadata'] = $conn_metadata;

        return $this;
    }

    /**
     * Gets peer_metadata
     *
     * @return \IdeaEngine\TezosSDK\Model\InlineResponse2009PeerMetadata
     */
    public function getPeerMetadata()
    {
        return $this->container['peer_metadata'];
    }

    /**
     * Sets peer_metadata
     *
     * @param \IdeaEngine\TezosSDK\Model\InlineResponse2009PeerMetadata $peer_metadata peer_metadata
     *
     * @return self
     */
    public function setPeerMetadata($peer_metadata)
    {
        $this->container['peer_metadata'] = $peer_metadata;

        return $this;
    }

    /**
     * Gets state
     *
     * @return \IdeaEngine\TezosSDK\Model\P2pPeerState
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param \IdeaEngine\TezosSDK\Model\P2pPeerState $state state
     *
     * @return self
     */
    public function setState($state)
    {
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets reachable_at
     *
     * @return \IdeaEngine\TezosSDK\Model\P2pConnectionId|null
     */
    public function getReachableAt()
    {
        return $this->container['reachable_at'];
    }

    /**
     * Sets reachable_at
     *
     * @param \IdeaEngine\TezosSDK\Model\P2pConnectionId|null $reachable_at reachable_at
     *
     * @return self
     */
    public function setReachableAt($reachable_at)
    {
        $this->container['reachable_at'] = $reachable_at;

        return $this;
    }

    /**
     * Gets stat
     *
     * @return \IdeaEngine\TezosSDK\Model\P2pStat
     */
    public function getStat()
    {
        return $this->container['stat'];
    }

    /**
     * Sets stat
     *
     * @param \IdeaEngine\TezosSDK\Model\P2pStat $stat stat
     *
     * @return self
     */
    public function setStat($stat)
    {
        $this->container['stat'] = $stat;

        return $this;
    }

    /**
     * Gets last_failed_connection
     *
     * @return OneOfP2pConnectionIdTimestampSystem[]|null
     */
    public function getLastFailedConnection()
    {
        return $this->container['last_failed_connection'];
    }

    /**
     * Sets last_failed_connection
     *
     * @param OneOfP2pConnectionIdTimestampSystem[]|null $last_failed_connection last_failed_connection
     *
     * @return self
     */
    public function setLastFailedConnection($last_failed_connection)
    {
        $this->container['last_failed_connection'] = $last_failed_connection;

        return $this;
    }

    /**
     * Gets last_rejected_connection
     *
     * @return OneOfP2pConnectionIdTimestampSystem[]|null
     */
    public function getLastRejectedConnection()
    {
        return $this->container['last_rejected_connection'];
    }

    /**
     * Sets last_rejected_connection
     *
     * @param OneOfP2pConnectionIdTimestampSystem[]|null $last_rejected_connection last_rejected_connection
     *
     * @return self
     */
    public function setLastRejectedConnection($last_rejected_connection)
    {
        $this->container['last_rejected_connection'] = $last_rejected_connection;

        return $this;
    }

    /**
     * Gets last_established_connection
     *
     * @return OneOfP2pConnectionIdTimestampSystem[]|null
     */
    public function getLastEstablishedConnection()
    {
        return $this->container['last_established_connection'];
    }

    /**
     * Sets last_established_connection
     *
     * @param OneOfP2pConnectionIdTimestampSystem[]|null $last_established_connection last_established_connection
     *
     * @return self
     */
    public function setLastEstablishedConnection($last_established_connection)
    {
        $this->container['last_established_connection'] = $last_established_connection;

        return $this;
    }

    /**
     * Gets last_disconnection
     *
     * @return OneOfP2pConnectionIdTimestampSystem[]|null
     */
    public function getLastDisconnection()
    {
        return $this->container['last_disconnection'];
    }

    /**
     * Sets last_disconnection
     *
     * @param OneOfP2pConnectionIdTimestampSystem[]|null $last_disconnection last_disconnection
     *
     * @return self
     */
    public function setLastDisconnection($last_disconnection)
    {
        $this->container['last_disconnection'] = $last_disconnection;

        return $this;
    }

    /**
     * Gets last_seen
     *
     * @return OneOfP2pConnectionIdTimestampSystem[]|null
     */
    public function getLastSeen()
    {
        return $this->container['last_seen'];
    }

    /**
     * Sets last_seen
     *
     * @param OneOfP2pConnectionIdTimestampSystem[]|null $last_seen last_seen
     *
     * @return self
     */
    public function setLastSeen($last_seen)
    {
        $this->container['last_seen'] = $last_seen;

        return $this;
    }

    /**
     * Gets last_miss
     *
     * @return OneOfP2pConnectionIdTimestampSystem[]|null
     */
    public function getLastMiss()
    {
        return $this->container['last_miss'];
    }

    /**
     * Sets last_miss
     *
     * @param OneOfP2pConnectionIdTimestampSystem[]|null $last_miss last_miss
     *
     * @return self
     */
    public function setLastMiss($last_miss)
    {
        $this->container['last_miss'] = $last_miss;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


