<?php
/**
 * P2pPeerState
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  IdeaEngine\TezosSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 11.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IdeaEngine\TezosSDK\Model;
use \IdeaEngine\TezosSDK\ObjectSerializer;

/**
 * P2pPeerState Class Doc Comment
 *
 * @category Class
 * @description The state a peer connection can be in: accepted (when the connection is being established), running (when the connection is already established), disconnected (otherwise).
 * @package  IdeaEngine\TezosSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class P2pPeerState
{
    /**
     * Possible values of this enum
     */
    const RUNNING = 'running';

    const ACCEPTED = 'accepted';

    const DISCONNECTED = 'disconnected';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::RUNNING,
            self::ACCEPTED,
            self::DISCONNECTED
        ];
    }
}


