<?php
/**
 * WorkersChainValidatorsChainIdPeersValidatorsPipelines
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  IdeaEngine\TezosSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 11.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IdeaEngine\TezosSDK\Model;

use \ArrayAccess;
use \IdeaEngine\TezosSDK\ObjectSerializer;

/**
 * WorkersChainValidatorsChainIdPeersValidatorsPipelines Class Doc Comment
 *
 * @category Class
 * @package  IdeaEngine\TezosSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class WorkersChainValidatorsChainIdPeersValidatorsPipelines implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = '_workers_chain_validators__chain_id__peers_validators_pipelines';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'fetched_headers' => 'int',
        'fetched_blocks' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'fetched_headers' => null,
        'fetched_blocks' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'fetched_headers' => 'fetched_headers',
        'fetched_blocks' => 'fetched_blocks'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'fetched_headers' => 'setFetchedHeaders',
        'fetched_blocks' => 'setFetchedBlocks'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'fetched_headers' => 'getFetchedHeaders',
        'fetched_blocks' => 'getFetchedBlocks'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['fetched_headers'] = $data['fetched_headers'] ?? null;
        $this->container['fetched_blocks'] = $data['fetched_blocks'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['fetched_headers'] === null) {
            $invalidProperties[] = "'fetched_headers' can't be null";
        }
        if (($this->container['fetched_headers'] > 1073741823)) {
            $invalidProperties[] = "invalid value for 'fetched_headers', must be smaller than or equal to 1073741823.";
        }

        if (($this->container['fetched_headers'] < -1073741824)) {
            $invalidProperties[] = "invalid value for 'fetched_headers', must be bigger than or equal to -1073741824.";
        }

        if ($this->container['fetched_blocks'] === null) {
            $invalidProperties[] = "'fetched_blocks' can't be null";
        }
        if (($this->container['fetched_blocks'] > 1073741823)) {
            $invalidProperties[] = "invalid value for 'fetched_blocks', must be smaller than or equal to 1073741823.";
        }

        if (($this->container['fetched_blocks'] < -1073741824)) {
            $invalidProperties[] = "invalid value for 'fetched_blocks', must be bigger than or equal to -1073741824.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets fetched_headers
     *
     * @return int
     */
    public function getFetchedHeaders()
    {
        return $this->container['fetched_headers'];
    }

    /**
     * Sets fetched_headers
     *
     * @param int $fetched_headers fetched_headers
     *
     * @return self
     */
    public function setFetchedHeaders($fetched_headers)
    {

        if (($fetched_headers > 1073741823)) {
            throw new \InvalidArgumentException('invalid value for $fetched_headers when calling WorkersChainValidatorsChainIdPeersValidatorsPipelines., must be smaller than or equal to 1073741823.');
        }
        if (($fetched_headers < -1073741824)) {
            throw new \InvalidArgumentException('invalid value for $fetched_headers when calling WorkersChainValidatorsChainIdPeersValidatorsPipelines., must be bigger than or equal to -1073741824.');
        }

        $this->container['fetched_headers'] = $fetched_headers;

        return $this;
    }

    /**
     * Gets fetched_blocks
     *
     * @return int
     */
    public function getFetchedBlocks()
    {
        return $this->container['fetched_blocks'];
    }

    /**
     * Sets fetched_blocks
     *
     * @param int $fetched_blocks fetched_blocks
     *
     * @return self
     */
    public function setFetchedBlocks($fetched_blocks)
    {

        if (($fetched_blocks > 1073741823)) {
            throw new \InvalidArgumentException('invalid value for $fetched_blocks when calling WorkersChainValidatorsChainIdPeersValidatorsPipelines., must be smaller than or equal to 1073741823.');
        }
        if (($fetched_blocks < -1073741824)) {
            throw new \InvalidArgumentException('invalid value for $fetched_blocks when calling WorkersChainValidatorsChainIdPeersValidatorsPipelines., must be bigger than or equal to -1073741824.');
        }

        $this->container['fetched_blocks'] = $fetched_blocks;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


