<?php
/**
 * ChainStatusTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  IdeaEngine\TezosSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 11.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace IdeaEngine\TezosSDK\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ChainStatusTest Class Doc Comment
 *
 * @category    Class
 * @description If &#39;unsynced&#39;, the node is not currently synchronized with of its peers (it is probably still bootstrapping and its head is lagging behind the chain&#39;s). If &#39;synced&#39;, the node considers itself synchronized with its peers and the current head timestamp is recent. If &#39;stuck&#39;, the node considers itself synchronized with its peers but the chain seems to be halted from its viewpoint.
 * @package     IdeaEngine\TezosSDK
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ChainStatusTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ChainStatus"
     */
    public function testChainStatus()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
