<?php
/**
 * DefaultApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  IdeaEngine\TezosSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Tezos RPC
 *
 * Tezos client RPC API.
 *
 * The version of the OpenAPI document: 11.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace IdeaEngine\TezosSDK\Test\Api;

use \IdeaEngine\TezosSDK\Configuration;
use \IdeaEngine\TezosSDK\ApiException;
use \IdeaEngine\TezosSDK\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  IdeaEngine\TezosSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for chainsChainIdBlocksGet
     *
     * .
     *
     */
    public function testChainsChainIdBlocksGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for chainsChainIdChainIdGet
     *
     * .
     *
     */
    public function testChainsChainIdChainIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for chainsChainIdCheckpointGet
     *
     * .
     *
     */
    public function testChainsChainIdCheckpointGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for chainsChainIdInvalidBlocksBlockHashDelete
     *
     * .
     *
     */
    public function testChainsChainIdInvalidBlocksBlockHashDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for chainsChainIdInvalidBlocksBlockHashGet
     *
     * .
     *
     */
    public function testChainsChainIdInvalidBlocksBlockHashGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for chainsChainIdInvalidBlocksGet
     *
     * .
     *
     */
    public function testChainsChainIdInvalidBlocksGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for chainsChainIdIsBootstrappedGet
     *
     * .
     *
     */
    public function testChainsChainIdIsBootstrappedGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for chainsChainIdLevelsCabooseGet
     *
     * .
     *
     */
    public function testChainsChainIdLevelsCabooseGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for chainsChainIdLevelsCheckpointGet
     *
     * .
     *
     */
    public function testChainsChainIdLevelsCheckpointGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for chainsChainIdLevelsSavepointGet
     *
     * .
     *
     */
    public function testChainsChainIdLevelsSavepointGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for chainsChainIdPatch
     *
     * .
     *
     */
    public function testChainsChainIdPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for configGet
     *
     * .
     *
     */
    public function testConfigGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for configHistoryModeGet
     *
     * .
     *
     */
    public function testConfigHistoryModeGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for configNetworkUserActivatedProtocolOverridesGet
     *
     * .
     *
     */
    public function testConfigNetworkUserActivatedProtocolOverridesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for configNetworkUserActivatedUpgradesGet
     *
     * .
     *
     */
    public function testConfigNetworkUserActivatedUpgradesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for errorsGet
     *
     * .
     *
     */
    public function testErrorsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for fetchProtocolProtocolHashGet
     *
     * .
     *
     */
    public function testFetchProtocolProtocolHashGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for injectionBlockPost
     *
     * .
     *
     */
    public function testInjectionBlockPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for injectionOperationPost
     *
     * .
     *
     */
    public function testInjectionOperationPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for injectionProtocolPost
     *
     * .
     *
     */
    public function testInjectionProtocolPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for monitorActiveChainsGet
     *
     * .
     *
     */
    public function testMonitorActiveChainsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for monitorBootstrappedGet
     *
     * .
     *
     */
    public function testMonitorBootstrappedGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for monitorCommitHashGet
     *
     * .
     *
     */
    public function testMonitorCommitHashGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for monitorHeadsChainIdGet
     *
     * .
     *
     */
    public function testMonitorHeadsChainIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for monitorProtocolsGet
     *
     * .
     *
     */
    public function testMonitorProtocolsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for monitorValidBlocksGet
     *
     * .
     *
     */
    public function testMonitorValidBlocksGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkConnectionsGet
     *
     * .
     *
     */
    public function testNetworkConnectionsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkConnectionsPeerIdDelete
     *
     * .
     *
     */
    public function testNetworkConnectionsPeerIdDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkConnectionsPeerIdGet
     *
     * .
     *
     */
    public function testNetworkConnectionsPeerIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkGreylistClearGet
     *
     * .
     *
     */
    public function testNetworkGreylistClearGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkGreylistDelete
     *
     * .
     *
     */
    public function testNetworkGreylistDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkGreylistIpsGet
     *
     * .
     *
     */
    public function testNetworkGreylistIpsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkGreylistPeersGet
     *
     * .
     *
     */
    public function testNetworkGreylistPeersGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkLogGet
     *
     * .
     *
     */
    public function testNetworkLogGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkPeersGet
     *
     * .
     *
     */
    public function testNetworkPeersGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkPeersPeerIdBanGet
     *
     * .
     *
     */
    public function testNetworkPeersPeerIdBanGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkPeersPeerIdBannedGet
     *
     * .
     *
     */
    public function testNetworkPeersPeerIdBannedGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkPeersPeerIdGet
     *
     * .
     *
     */
    public function testNetworkPeersPeerIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkPeersPeerIdLogGet
     *
     * .
     *
     */
    public function testNetworkPeersPeerIdLogGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkPeersPeerIdPatch
     *
     * .
     *
     */
    public function testNetworkPeersPeerIdPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkPeersPeerIdTrustGet
     *
     * .
     *
     */
    public function testNetworkPeersPeerIdTrustGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkPeersPeerIdUnbanGet
     *
     * .
     *
     */
    public function testNetworkPeersPeerIdUnbanGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkPeersPeerIdUntrustGet
     *
     * .
     *
     */
    public function testNetworkPeersPeerIdUntrustGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkPointsGet
     *
     * .
     *
     */
    public function testNetworkPointsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkPointsPointBanGet
     *
     * .
     *
     */
    public function testNetworkPointsPointBanGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkPointsPointBannedGet
     *
     * .
     *
     */
    public function testNetworkPointsPointBannedGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkPointsPointGet
     *
     * .
     *
     */
    public function testNetworkPointsPointGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkPointsPointLogGet
     *
     * .
     *
     */
    public function testNetworkPointsPointLogGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkPointsPointPatch
     *
     * .
     *
     */
    public function testNetworkPointsPointPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkPointsPointPut
     *
     * .
     *
     */
    public function testNetworkPointsPointPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkPointsPointTrustGet
     *
     * .
     *
     */
    public function testNetworkPointsPointTrustGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkPointsPointUnbanGet
     *
     * .
     *
     */
    public function testNetworkPointsPointUnbanGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkPointsPointUntrustGet
     *
     * .
     *
     */
    public function testNetworkPointsPointUntrustGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkSelfGet
     *
     * .
     *
     */
    public function testNetworkSelfGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkStatGet
     *
     * .
     *
     */
    public function testNetworkStatGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkVersionGet
     *
     * .
     *
     */
    public function testNetworkVersionGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for networkVersionsGet
     *
     * .
     *
     */
    public function testNetworkVersionsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for protocolsGet
     *
     * .
     *
     */
    public function testProtocolsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for protocolsProtocolHashEnvironmentGet
     *
     * .
     *
     */
    public function testProtocolsProtocolHashEnvironmentGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for protocolsProtocolHashGet
     *
     * .
     *
     */
    public function testProtocolsProtocolHashGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for statsGcGet
     *
     * .
     *
     */
    public function testStatsGcGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for statsMemoryGet
     *
     * .
     *
     */
    public function testStatsMemoryGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for versionGet
     *
     * .
     *
     */
    public function testVersionGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workersBlockValidatorGet
     *
     * .
     *
     */
    public function testWorkersBlockValidatorGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workersChainValidatorsChainIdDdbGet
     *
     * .
     *
     */
    public function testWorkersChainValidatorsChainIdDdbGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workersChainValidatorsChainIdGet
     *
     * .
     *
     */
    public function testWorkersChainValidatorsChainIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workersChainValidatorsChainIdPeersValidatorsGet
     *
     * .
     *
     */
    public function testWorkersChainValidatorsChainIdPeersValidatorsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workersChainValidatorsChainIdPeersValidatorsPeerIdGet
     *
     * .
     *
     */
    public function testWorkersChainValidatorsChainIdPeersValidatorsPeerIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workersChainValidatorsGet
     *
     * .
     *
     */
    public function testWorkersChainValidatorsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workersPrevalidatorsChainIdGet
     *
     * .
     *
     */
    public function testWorkersPrevalidatorsChainIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workersPrevalidatorsGet
     *
     * .
     *
     */
    public function testWorkersPrevalidatorsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
